1. Import the numpy package under the name np (★☆☆)

In [5]:
import numpy as np

1.24.0


2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)

3. Create a null vector of size 10 (★☆☆)

In [7]:
null_vector = np.zeros(10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
null_vector_sec = np.zeros(10)
null_vector_sec[4] = 1

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
vector = np.arange(10, 50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last) (★☆☆)

In [97]:
vector = vector[::-1]

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
matrix = np.arange(0, 9).reshape(3, 3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
vector_sec = [1, 2, 0, 0, 4, 0]
for elem in vector_sec:
    if elem != 0:
        print(vector_sec.index(elem))

0
1
4


11. Create a 3x3 identity matrix (★☆☆)

In [15]:
matrix_identity = np.identity(3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
import random
array = np.random.random((3, 3, 3))

[[[0.80921723 0.54268369 0.45530205]
  [0.8592958  0.14353476 0.34909432]
  [0.57066562 0.72639847 0.30941867]]

 [[0.02885841 0.31881369 0.84443905]
  [0.90294466 0.83677744 0.33564003]
  [0.63261214 0.72605031 0.28497999]]

 [[0.8567467  0.71057648 0.50909163]
  [0.51664135 0.01882926 0.96735054]
  [0.48069859 0.68274086 0.65090662]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [21]:
array_new = np.random.random((10, 10))
minimum = array_new.min()
maximum = array_new.max()

[[0.70746582 0.83751282 0.08463434 0.81569981 0.47511827 0.66156051
  0.10900349 0.67451863 0.8685436  0.74097968]
 [0.87933274 0.08609954 0.03977697 0.20769917 0.71692376 0.34162844
  0.86161816 0.23441099 0.15057702 0.64398178]
 [0.31941162 0.13929362 0.53630221 0.77825731 0.48062172 0.25425294
  0.56913801 0.10238471 0.75968762 0.4085381 ]
 [0.39406283 0.23386419 0.34041538 0.50064709 0.77832056 0.56168896
  0.8854819  0.75307512 0.71655326 0.97874523]
 [0.90260874 0.81624176 0.97957527 0.29269667 0.19835291 0.95667064
  0.30367117 0.7348582  0.67712955 0.78814268]
 [0.09979144 0.13055749 0.4666435  0.04875786 0.48756104 0.49657043
  0.11352036 0.4774261  0.67766808 0.34322672]
 [0.97626559 0.14379254 0.13718953 0.56057326 0.38418995 0.79410434
  0.24217701 0.22252654 0.08091171 0.60453891]
 [0.21222632 0.50990785 0.44930802 0.12651048 0.31640091 0.62652731
  0.15997001 0.34812598 0.43652035 0.42609173]
 [0.04446947 0.13001416 0.90927224 0.54763914 0.82211351 0.01632241
  0.75284657

14. Create a random vector of size 30 and find the mean value (★☆☆)

In [24]:
random_vector = np.random.random(30)
mean_value = random_vector.mean()

[0.20436706 0.54744643 0.26208035 0.15481643 0.04338695 0.45802489
 0.18983874 0.01168502 0.83655319 0.29286491 0.2271274  0.46201973
 0.38177106 0.22230996 0.75872916 0.25047047 0.56171212 0.52405299
 0.28819686 0.56291714 0.51501495 0.26165661 0.46342768 0.91698079
 0.66315575 0.69847269 0.48473275 0.60709473 0.53654346 0.73447653] 0.43739756106913513


In [25]:
array_2d = np.ones((random.randint(3, 6), random.randint(3, 6)))
array_2d[1:-1, 1:-1] = 0

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

In [38]:
0 * np.nan #  nan
np.nan == np.nan #  False
np.inf > np.nan #  False
np.nan - np.nan #  nan
np.nan in set([np.nan]) #  True
0.3 == 3 * 0.1 #  False

False

19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [39]:
matrix_eight = np.zeros((8, 8))
matrix_eight[1::2, ::2] = 1
matrix_eight[::2, 1::2] = 1

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [43]:
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [44]:
arr = np.arange(11)
arr[(3 < arr) & (arr < 8)] *= -1

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


28. What are the result of the following expressions? (★☆☆)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [47]:
np.array(0) / np.array(0) #  nan
np.array(0) // np.array(0) #  0
np.array([np.nan]).astype(int).astype(float) #  array([-9.22337204e+18])

/var/folders/k7/t4wcx5c91hg141g_z8r9nmbh0000gp/T/ipykernel_9056/1202261281.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

30. How to find common values between two arrays? (★☆☆)

In [64]:
array_1 = np.array([random.randint(0, 4) for i in range(10)])
array_2 = np.array([random.randint(0, 4) for i in range(10)])
print(array_1, array_2)
print(np.intersect1d(array_1, array_2))

[1 2 1 2 0 3 3 2 3 2] [4 1 4 1 1 4 0 2 2 0]
[0 1 2]


40. Create a random vector of size 10 and sort it (★★☆)

In [69]:
ran_vector = sorted(np.random.random(10))
#  или
ran_vector = np.random.random(10)
ran_vector.sort()

[0.10617671 0.12953375 0.15045287 0.16741929 0.25883882 0.47664666
 0.48434587 0.52939972 0.54300928 0.61800703]


42. Consider two random array A and B, check if they are equal (★★☆)

In [73]:
array_A, array_B = np.random.random(5), np.random.random(5)
np.allclose(array_A, array_B)

False

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [83]:
ran_matrix = np.random.random((10, 2))
x, y = ran_matrix[:, 0], ran_matrix[:, 1]
coords = np.array((*np.sqrt(x ** 2 + y ** 2), *np.arctan2(y, x)))

[0.62046528 0.55475337 0.59106559 0.6754303  0.57230405 0.53180139
 0.34584291 0.4804758  0.51354632 0.91496171 0.76890843 1.39316928
 0.94989313 0.00842559 1.45311718 0.50498298 0.68105734 1.30774251
 0.30577968 0.53248284]


53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [91]:
a = (np.random.rand(10)*100).astype(np.float32)
b = a.view(np.int32)
b[:] = a

[57 28 69 46  0 58 41 42 81 70]


58. Subtract the mean of each row of a matrix (★★☆)

In [96]:
m = np.random.random((10, 10))
m -= m.mean(axis=1).reshape(-1, 1)

[[ 0.15839622 -0.31758348  0.28067849 -0.09562406 -0.17506947 -0.31602088
   0.08614203 -0.37716829  0.43565546  0.32059396]
 [-0.01007651  0.16281199 -0.34668157 -0.22917952  0.25546972  0.39656664
   0.39486992 -0.25179779  0.20266056 -0.57464343]
 [ 0.39648129 -0.12768345 -0.16342311  0.31267391 -0.21319642 -0.2081899
   0.33719805 -0.33315856 -0.23533827  0.23463646]
 [ 0.39350963 -0.00584402 -0.1395457  -0.11442535 -0.38897838 -0.22351724
   0.2750129   0.13315122  0.29630531 -0.22566837]
 [-0.13880828  0.17772229 -0.2113539  -0.00720884  0.48281465  0.24076713
  -0.22443907 -0.2069473  -0.1059929  -0.00655378]
 [-0.05263958 -0.44915372  0.27481303 -0.1450632   0.29460208 -0.0624108
   0.06135738  0.49199426 -0.22147965 -0.1920198 ]
 [ 0.22770562  0.26600437 -0.12755266 -0.19155666 -0.03218269 -0.36277974
  -0.22315991  0.26217525  0.09178575  0.08956067]
 [ 0.29887862 -0.1195781  -0.4146942  -0.34354451 -0.14410494  0.023982
  -0.26350825  0.02739444  0.54606051  0.38911442]
 [-0